[pod-gateway] Fix issue where values.yaml defined 'configFile' wouldn't work in vpn addon
k8s-at-home/charts pull request #1061
Opened 2021-06-24 02:32 UTC by jmmaloney4

**Description of the change**

Because the default values.yaml file has `configFileSecret` set to `openvpn` by default, it is impossible to use the built in `configFile` with no secret. If you attempt to override `configFileSecret` to `null` the default value takes precedence, and the gateway will not start because of the lack of `openvpn` secret. 

**Benefits**

**Possible drawbacks**

**Applicable issues**

- fixes #

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

2021-06-24 06:40 UTC, bjw-s commented
In my local testing, when you specify the following values you should be able to run without the configFile:

```yaml
addons:
  vpn:
    enabled: true
    type: openvpn
    openvpn:
    configFileSecret: 
```

Although I do think it would be a bit cleaner if some of these keys are not set here but are left to the user's preference. Unfortunately I ran into a small bug in the common library when trying this, so that would need to get fixed before we can remove the `openvpn` and `wireguard` keys.

2021-06-24 11:58 UTC, angelnu commented
Thanks for the PR!

The values I picked as the defaults were heavily influenced by me using openvpn - so we can remove any non-default values that cannot be overwritten by the user.

Is there anything to remove beyond `configFileSecret` and potentially `type` ? Is there any issue with the null values @bjw-s or are they merged with the common defaults?

2021-06-24 12:03 UTC, bjw-s commented
> Is there anything to remove beyond `configFileSecret` and potentially `type` ? Is there any issue with the null values @bjw-s or are they merged with the common defaults?

By specifying them as null-values, the default values seem to get overwritten with `null` (I still can't really figure out why :X), potentially causing the chart to render incorrectly. That's why I proposed to remove the `wireguard` and `openvpn` keys.

2021-06-24 12:29 UTC, angelnu requested changes

2021-06-24 12:29 UTC, angelnu commented on charts/stable/pod-gateway/values.yaml
>      openvpn:
```suggestion
    # openvpn:
```

2021-06-24 12:29 UTC, angelnu commented on charts/stable/pod-gateway/values.yaml
>      wireguard:
```suggestion
    # wireguard:
```

2021-06-24 12:29 UTC, angelnu commented on charts/stable/pod-gateway/values.yaml
>      env:
```suggestion
    # env:
```

2021-06-25 08:18 UTC, angelnu commented
@jmmaloney4 - please merge the suggestions when you have the chance so we can merge your PR. Thanks again for submitting 👍

2021-06-28 10:47 UTC, angelnu commented
@jmmaloney4 - would you be able to add the docs? If you need any help please let me know - I can, if necessary, add the doc to your PR so we can merge this fix.

2021-06-28 15:06 UTC, jmmaloney4 commented
@angelnu is this change sufficient?

2021-06-28 15:38 UTC, angelnu commented
It looks good @jmmaloney4 - only step left is to re-generate the README.md.

Can you please run `task chart:helm-docs CHART_TYPE=stable CHART=pod-gateway` in your PR? Then we are ready to merge :-)

2021-06-28 16:40 UTC, jmmaloney4 commented
@angelnu should be good to go.

2021-06-28 16:47 UTC, angelnu approved these changes

2021-06-28 16:48 UTC, angelnu commented
Thanks @jmmaloney4 - now we need an owner to merge.

2021-06-28 17:23 UTC, bjw-s approved these changes
Approved! Thanks a lot for the contribution!!

2021-06-28 17:24 UTC, merged

2021-06-28 17:24 UTC, bjw-s commented
@all-contributors please add @jmmaloney4 for code