[changedetection-io] Adding chart
k8s-at-home/charts pull request #1141
Opened 2021-08-27 14:32 UTC by tuxpeople

**Description of the change**

adding chart for changedetection.io

**Additional information**

I tried to follow https://docs.k8s-at-home.com/our-helm-charts/development/creating-a-new-chart/ to close #1140

**Checklist** 
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)

2021-08-29 08:49 UTC, bjw-s requested changes
Thanks for taking the time to create this PR! 🥇 The changes look good overall, just a small change requested in the persistence section.

2021-08-29 08:49 UTC, bjw-s commented on charts/incubator/changedetection-io/values.yaml
> +    type: emptyDir
```suggestion
```

I would remove this line, since I can imagine that the app needs actual persistence across Pod lifecycles for the data folder.

2021-08-29 18:20 UTC, bjw-s requested changes

2021-08-29 18:20 UTC, bjw-s commented on charts/incubator/changedetection-io/values.yaml
> +  tag: 0.93
```suggestion
  tag: "0.93"
```

2021-08-30 14:52 UTC, tuxpeople commented
> Thanks for taking the time to create this PR! 🥇 The changes look good overall, just a small change requested in the persistence section.

Thanks for your constructive feedback. Yes, you're right. I committed the proposed changes.

As I'm a new to this project, do you have some sort of automation for image updates? Or shall I try to keep an eye on updates of the upstream docker image and bump the chart accordingly? Is there documentation regarding the versioning? I know its semantic versioning, but I assume bumping the image tag is just a minor upgrade?

2021-08-30 16:47 UTC, bjw-s commented
Looks like the CI now fails because the image can't be found. Are you sure you are pointing it at the correct one?

2021-08-31 07:20 UTC, tuxpeople commented
> Looks like the CI now fails because the image can't be found. Are you sure you are pointing it at the correct one?

For some reasons `0.93` is not the same as `0.39` :D It's fixed now, sorry

2021-09-01 05:32 UTC, bjw-s approved these changes

2021-09-01 05:33 UTC, bjw-s commented
Looks good, thanks for submitting this! 👍

2021-09-01 05:33 UTC, merged

2021-09-01 08:06 UTC, tuxpeople commented
thanks @bjw-s !

how is the process from incubator to "graduated"? :-)