[openhab] Add new chart.
k8s-at-home/charts pull request #1232
Opened 2021-10-04 09:00 UTC by reitermarkus

**Description of the change**

Add chart for OpenHAB.

**Benefits**

N/A

**Possible drawbacks**

N/A

**Applicable issues**

N/A

**Additional information**

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [ ] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

2021-10-04 18:05 UTC, bjw-s commented on charts/incubator/openhab/values.yaml
> +# -- Configure persistence settings for the chart under this key.
I would put a remark here indicating that the user should select one of the two approaches.

2021-10-04 18:07 UTC, bjw-s requested changes
Thanks for taking the time to make this chart and submitting the PR! 🍻 

The change looks good in general, just a small textual requested to provide some clarification to the users. Once that's updated and the README regenerated I'll approve merge it :)

2021-10-04 22:42 UTC, reitermarkus commented
Added clarification for volume options.

2021-10-06 13:13 UTC, onedr0p approved these changes

2021-10-06 13:13 UTC, merged

2021-10-06 13:13 UTC, onedr0p commented
@all-contributors please add @reitermarkus for code