[frigate] update frigate version to 0.9.4
k8s-at-home/charts pull request #1306
Opened 2021-12-12 10:11 UTC by PixelJonas

**Description of the change**

This PR bumps frigate version to 0.9.4 and the chart-version to 7.0.0 as frigate introduced breaking changes to the config file. README.md is adjusted accordingly

**Benefits**

I just started installing frigate and there was a big mismatch between frigate documentation of configuration and the one needed for the version used in this chart. The new frigate version also includes better error messages for missing configuration, which should make the upgrade easy.

**Additional information**

Most of my configuration errors were based on custom camera configuration.

*v0.8.x*
```
...
camera:
  width: 640
  height: 360
  fps: 4
...
```

*v0.9.x*
```
...
camera:
  detect:
    width: 640
    height: 360
    fps: 4
...
```

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [X] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

2021-12-12 10:26 UTC, PixelJonas commented
mhhh chart installs fails because there is no camera configured per default. I don't know if our `values.yaml` should configure any default camera as the camera has to have a unique key which may introduce faulty configuration to users.


```
[2021-12-12 10:20:34] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
1 validation error for FrigateConfig
cameras
  field required (type=value_error.missing)
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
```

2021-12-12 12:01 UTC, onedr0p commented
Before doing the above you can create a `ci/ct-values.yaml` with values that only get used in the CI.

2021-12-12 12:02 UTC, PixelJonas commented
let me check if I can find a configuration for a dummy-camera and update the PR

2021-12-12 12:05 UTC, PixelJonas commented
can you elaborate on the `incomplete-docs` tag? Did I miss something? AFAIK I updated the `version`, added the `README_CHANGELOG.md.gotmpl` entry 🤔

2021-12-12 12:15 UTC, onedr0p commented
Happy trigger finger on me I guess lol. I would suggest not formatting the yaml files. I'm seeing some changes there.

2021-12-29 19:07 UTC, onedr0p requested changes

2021-12-29 19:07 UTC, onedr0p commented on charts/stable/frigate/Chart.yaml
> +  - machine-learning
Don't need to indent

2021-12-29 19:07 UTC, onedr0p commented on charts/stable/frigate/Chart.yaml
> +  - https://github.com/blakeblackshear/frigate
Don't need to indent

2021-12-29 19:07 UTC, onedr0p commented on charts/stable/frigate/Chart.yaml
> +    email: 5434875+PixelJonas@users.noreply.github.com
Don't need to indent

2021-12-29 19:07 UTC, onedr0p commented on charts/stable/frigate/Chart.yaml
> +    version: 4.2.0
Don't need to indent

2021-12-29 19:07 UTC, onedr0p commented on charts/stable/frigate/values.yaml
> +  {}
Formatting should have the {} on the same like like before

2021-12-30 02:38 UTC, onedr0p approved these changes

2021-12-30 02:38 UTC, merged

2021-12-30 02:38 UTC, onedr0p commented
Thanks!