[facebox] initial release
k8s-at-home/charts pull request #1315
Opened 2021-12-17 21:34 UTC by runningman84

**Description of the change**
This chart can be used with double-take like deepstack.

**Benefits**

**Possible drawbacks**

**Applicable issues**

- fixes #

**Additional information**

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [ ] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

2021-12-19 00:08 UTC, onedr0p requested changes
I think you can sldo put this in the stable directory, not incubator.

2021-12-19 00:08 UTC, onedr0p commented on charts/incubator/facebox/ci/ct-values.yaml
> +    enabled: true
This looks like a bad copy/paste?

2021-12-26 17:07 UTC, runningman84 commented on charts/incubator/facebox/ci/ct-values.yaml
> +    enabled: true
yes I fixed that...

2021-12-29 19:59 UTC, onedr0p commented
```
[INFO]     facebox v1
:-(
	Ohh you're so close, but Machine Box requires your Box Key in order to work.

	Head over to machinebox.io/account to get your key, and use it
	as the value for the MB_KEY environment variable.

	If you get stuck, read our guide: machinebox.io/docs/setup/box-key

	See you on machinebox.io/account :)```

2021-12-29 20:00 UTC, onedr0p commented
You might need to exclude this chart from being installed as a tes, please add it to the list here in your PR

https://github.com/k8s-at-home/charts/blob/master/.github/ct-install.yaml#L7-L19

2022-01-03 15:54 UTC, bjw-s commented on charts/stable/facebox/Chart.yaml
> +  version: 4.2.0
```suggestion
  version: 4.3.0
```

2022-01-03 15:55 UTC, bjw-s approved these changes

2022-01-03 15:57 UTC, merged