[dendrite] Add dendrite helm chart
k8s-at-home/charts pull request #1319
Opened 2021-12-21 14:18 UTC by Jonnobrow

This is the initial version of a Dendrite helm chart that supports monolithic deployment.

**Description of the change**

Adds a new chart for deploying [Dendrite](https://github.com/matrix-org/dendrite), a matrix homeserver. 

It only supports the monolithic deployment but the dendrite installation documentation states:
> For most deployments, it is recommended to run in monolith mode with PostgreSQL databases.

**Benefits**
- Easy configuration use the values.yaml file
- Quick to install

**Possible drawbacks**
- No support for polylith deployments

**Applicable issues**
- implements #1269 

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [X] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

2021-12-24 09:56 UTC, bjw-s requested changes
Thanks a lot for taking the time to submit this PR! I've added some comments/suggestions, but in general the chart looks 🥇

2021-12-24 09:56 UTC, bjw-s commented on charts/incubator/dendrite/templates/dendrite-config.yaml
> +{{- $conn_max_lifetime := default -1 .Values.dendrite.database.conn_max_lifetime }}
Since these are already provided by the Helm values, these seem superfluous.

2021-12-24 09:56 UTC, bjw-s commented on charts/incubator/dendrite/templates/dendrite-config.yaml
> +
```suggestion
```

2021-12-24 09:56 UTC, bjw-s commented on charts/incubator/dendrite/templates/dendrite-config.yaml
> +{{- toYaml .Values.dendrite.components.client_api.turn | nindent 8 }}
```suggestion
        {{- toYaml .Values.dendrite.components.client_api.turn | nindent 8 }}
```

2021-12-24 09:56 UTC, bjw-s commented on charts/incubator/dendrite/templates/dendrite-config.yaml
> +{{- toYaml .Values.dendrite.components.app_service_api.config_files | nindent 8 }}
```suggestion
        {{- toYaml .Values.dendrite.components.app_service_api.config_files | nindent 8 }}
```

2021-12-24 09:56 UTC, bjw-s commented on charts/incubator/dendrite/templates/dendrite-config.yaml
> +{{- toYaml .Values.dendrite.components.federation_api.federation_certificates | nindent 8 }}
```suggestion
        {{- toYaml .Values.dendrite.components.federation_api.federation_certificates | nindent 8 }}
```

2021-12-24 09:56 UTC, bjw-s commented on charts/incubator/dendrite/templates/dendrite-config.yaml
> +{{- toYaml .Values.dendrite.components.federation_api.key_perspectives | nindent 8 }}
```suggestion
        {{- toYaml .Values.dendrite.components.federation_api.key_perspectives | nindent 8 }}
```

2021-12-24 09:56 UTC, bjw-s commented on charts/incubator/dendrite/templates/dendrite-config.yaml
> +{{- toYaml .Values.dendrite.components.media_api.thumbnail_sizes | nindent 8 }}
```suggestion
        {{- toYaml .Values.dendrite.components.media_api.thumbnail_sizes | nindent 8 }}
```

2021-12-24 09:56 UTC, bjw-s commented on charts/incubator/dendrite/templates/dendrite-config.yaml
> +{{- toYaml .Values.dendrite.tracing.jaeger | nindent 8 }}
```suggestion
        {{- toYaml .Values.dendrite.tracing.jaeger | nindent 8 }}
```

2021-12-24 09:56 UTC, bjw-s commented on charts/incubator/dendrite/templates/dendrite-config.yaml
> +{{- toYaml .Values.dendrite.logging | nindent 6 }}
```suggestion
      {{- toYaml .Values.dendrite.logging | nindent 6 }}
```

2021-12-24 09:56 UTC, bjw-s commented on charts/incubator/dendrite/values.yaml
> +# Configuratio for Dendrite.
```suggestion
# -- Configuration for Dendrite.
```

2021-12-24 09:56 UTC, bjw-s commented on charts/incubator/dendrite/values.yaml
> +    # @default -- See values.yaml
```suggestion
```

2021-12-24 09:56 UTC, bjw-s commented on charts/incubator/dendrite/values.yaml
> +    # @default -- See values.yaml
```suggestion
```

2021-12-24 09:56 UTC, bjw-s commented on charts/incubator/dendrite/values.yaml
> +    # @default -- See values.yaml
```suggestion
```

2021-12-24 09:56 UTC, bjw-s commented on charts/incubator/dendrite/values.yaml
> +    # @default -- See the values.yaml
```suggestion
```

2021-12-24 09:56 UTC, bjw-s commented on charts/incubator/dendrite/values.yaml
> +      # @default -- See values.yaml
```suggestion
```

2021-12-24 09:56 UTC, bjw-s commented on charts/incubator/dendrite/values.yaml
> +      # @default -- See values.yaml
```suggestion
```

2021-12-31 09:05 UTC, S7evinK requested changes
~~Not sure if `charts/incubator/dendrite/ci/ct-values.yaml` should be in the repo.~~ Oh, somehow didn't see the CI there.

2021-12-31 09:05 UTC, S7evinK commented on charts/incubator/dendrite/templates/dendrite-config.yaml
> +        cache_lifetime: {{ default 300 .Values.dendrite.global.dns_cache.cache_lifetime }}
Cache lifetime changed, see https://github.com/matrix-org/dendrite/pull/1926

2021-12-31 16:23 UTC, S7evinK commented
@Jonnobrow
If you want to add polylith mode, you can have a loook at my (newbie) Chart at https://github.com/S7evinK/dendrite-helm :)

2022-01-03 16:05 UTC, bjw-s commented on charts/incubator/dendrite/Chart.yaml
> +    version: 4.2.0
```suggestion
    version: 4.3.0
```

2022-01-03 16:05 UTC, bjw-s commented on charts/incubator/dendrite/Chart.yaml
> +    version: 10.13.14
```suggestion
    version: 10.14.2
```

2022-01-03 16:11 UTC, bjw-s approved these changes

2022-01-03 16:11 UTC, merged