[double-take] Make detectors and notifiers optional
k8s-at-home/charts pull request #1321
Opened 2021-12-22 20:20 UTC by Jonnobrow

**Description of the change**

Each detector and notifier (gotify) now contains an `enabled` field
which must be set to true to add that detector to the config, otherwise
it will be omitted.

**Benefits**
- There is no longer a requirement to use the `compreface` detector

**Possible drawbacks**
- Exisiting configurations will need to add the `enabled ` key to the `deepstack` and `facebox` detectors in order for their configuration to be added to the config map. 

**Applicable issues**

- fixes #1314

**Additional information**

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [X] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

2021-12-24 08:31 UTC, bjw-s requested changes

2021-12-24 08:31 UTC, bjw-s commented on charts/stable/double-take/templates/configmap.yaml
> +{{ toYaml $newInnerConfig | indent 8 }}
I would indent this "properly" with the rest of the code and then replace it with
`{{- toYaml $newInnerConfig | nindent 8 }}`. (adjust the 8 as required)

2021-12-24 08:31 UTC, bjw-s commented on charts/stable/double-take/templates/configmap.yaml
> +{{ toYaml $config | indent 6 }}
I would indent this "properly" with the rest of the code and then replace it with
`{{- toYaml $config | nindent 6 }}`. (adjust the 6 as required)

2021-12-24 08:31 UTC, bjw-s commented on charts/stable/double-take/values.yaml
> +      # number of seconds before the request times out and is aborted
```suggestion
      # -- number of seconds before the request times out and is aborted
```

2021-12-24 08:31 UTC, bjw-s commented on charts/stable/double-take/values.yaml
> +      # number of seconds before the request times out and is aborted
```suggestion
      # -- number of seconds before the request times out and is aborted
```

2021-12-24 08:31 UTC, bjw-s commented on charts/stable/double-take/values.yaml
> +      # @default -- see values.yaml
```suggestion
```

2021-12-24 08:31 UTC, bjw-s commented on charts/stable/double-take/values.yaml
> +      # @default -- see values.yaml
```suggestion
```

2021-12-24 08:31 UTC, bjw-s commented on charts/stable/double-take/values.yaml
> +      # -- enable or disable the compreface detector
```suggestion
      # -- enable or disable the facebox detector
```

2021-12-24 08:31 UTC, bjw-s commented on charts/stable/double-take/values.yaml
> +      # @default -- see values.yaml
```suggestion
```

2021-12-24 08:31 UTC, bjw-s commented on charts/stable/double-take/values.yaml
> +      # -- enable or disable the compreface detector
```suggestion
      # -- enable or disable the deepstack detector
```

2021-12-24 08:31 UTC, bjw-s commented on charts/stable/double-take/values.yaml
> +      # @default -- see values.yaml
```suggestion
```

2021-12-24 16:09 UTC, Jonnobrow commented
Thanks for the review! I have applied the suggested changes. Please let me know if there is anything else I can do 😃

2021-12-30 11:07 UTC, bjw-s approved these changes

2021-12-30 11:11 UTC, merged