[privatebin] Add privatebin helm chart
k8s-at-home/charts pull request #1361
Opened 2022-01-06 15:25 UTC by psych0d0g

**Description of the change**
 added parameterized helm chart to deploy PrivateBIN (a client encrypted self-hosted pastebin alternative)

**Benefits**

More deployable products ;)

**Possible drawbacks**

no known limitations yet

2022-01-06 19:08 UTC, bjw-s requested changes
Thanks for taking the time to create this PR! 🎖 I've left some comments.

Afterwards you can run `./hack/gen-helm-docs.sh stable <chart>` again to update the chart's `README.md` file.

If you have any questions, feel free to reach out!

2022-01-06 19:08 UTC, bjw-s commented on charts/incubator/privatebin/README_CHANGELOG.md.gotmpl
> +{{- define "custom.changelog.header" -}}
This file is no longer required with the latest version of our template.

2022-01-06 19:08 UTC, bjw-s commented on charts/incubator/privatebin/Chart.yaml
> +  condition: postgresql.enabled
Please add an annotation to the chart with the changes. Check out [the template chart](https://github.com/k8s-at-home/charts/blob/master/templates/chart/Chart.yaml) for an example.

2022-01-07 07:51 UTC, psych0d0g commented
Running `./hack/gen-helm-docs.sh stable privatebin` leads to:
WARN[2022-01-07T08:36:45+01:00] Error generating gotemplates for chart /.../k8sathome/charts/stable/privatebin: template: /.../k8sathome/charts/stable/privatebin:120: function "fromYaml" not defined 

did i miss anything?

2022-01-07 08:12 UTC, psych0d0g commented
> 

was fixed by using kah custom helm-docs version 0.1.1

2022-01-07 10:38 UTC, bjw-s requested changes
Looking good!! Just a few more changes requested, if you can get those in there I'll go ahead and approve/merge.

2022-01-07 10:38 UTC, bjw-s commented on charts/stable/privatebin/values.yaml
> +config:
```suggestion
# for a description of every setting
# @default -- See values.yaml
config:
```

2022-01-07 10:38 UTC, bjw-s commented on charts/stable/privatebin/templates/common.yaml
> +{{- $_ := set .Values.persistence "privatebin-config" (include "privatebin.configVolume" . | fromYaml) -}}
```suggestion
{{/* Append the hardcoded settings */}}
{{- define "privatebin.harcodedValues" -}}
  {{/* Append the configMap volume to the volumes */}}
  persistence:
    privatebin-config:
      enabled: true
      type: "configMap"
      name: "{{ include "common.names.fullname" . }}-config"
      mountPath: "/srv/cfg/conf.php"
      subPath: "conf.php"
  {{- end }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "privatebin.harcodedValues" . | fromYaml) -}}
```

We have (sort of unofficially) moved away from the previous style of injecting "hardcoded" values and moved to the pattern as I've laid out in my suggestion.

2022-01-07 10:38 UTC, bjw-s commented on charts/stable/privatebin/Chart.yaml
> +description: PrivateBin running on an Nginx, php-fpm & Alpine Linux stack
```suggestion
description: A minimalist, open source online pastebin running on an Nginx, php-fpm & Alpine Linux stack
```

2022-01-07 11:06 UTC, bjw-s commented on charts/stable/privatebin/Chart.yaml
> +      description: bump common chart version from 4.2.0 to 4.3.0
```suggestion
    - kind: added
      description: Initial chart version
```

2022-01-07 12:17 UTC, bjw-s approved these changes
LGTM! :🍻

2022-01-07 12:17 UTC, merged

2022-01-07 12:18 UTC, bjw-s commented
@all-contributors Please add @psych0d0g for code.