[traefik-forward-auth] Reuse existing secret.
k8s-at-home/charts pull request #1404
Opened 2022-02-06 14:57 UTC by reitermarkus

**Description of the change**

Don't generate a new secret on every upgrade.

**Benefits**

Does not result in “Not authorized” errors after an upgrade.

**Possible drawbacks**

N/A

**Applicable issues**

N/A

**Additional information**

**Checklist** 
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [x] Variables have been documented in the `values.yaml` file.

2022-02-06 18:49 UTC, bjw-s commented
Hi! Thanks for creating this PR! 

I'm wondering if instead it would be possible to provide the user with an option to specify an `existingSecret`? That seems to be an approach that I've seen in other charts as well. That way we don't rely on the naming logic, and the behavior would be more explicit.

So if `.Values.existingSecret` is set, that is _always_ used and no new Secret object is created. 
If `.Values.secret` is set, the Secret object is created/managed by Helm with the specified value, and if neither is set a new random secret is generated.

2022-02-07 09:40 UTC, reitermarkus commented
Currently, it is possible to set either `secret` or `cookie.secret` or both, so this wouldn't quite map easily to a single `existingSecret`.

We could do the same thing as I did in https://github.com/k8s-at-home/charts/pull/1403 with `env.TS3SERVER_SERVERADMIN_PASSWORD` and check if `env.SECRET` or `env.COOKIE_SECRET` is already set.

This way a user can set the secret directly with `env.SECRET` or use e.g. `env.SECRET.secretKeyRef`.

2022-02-07 19:29 UTC, bjw-s commented
> Currently, it is possible to set either `secret` or `cookie.secret` or both, so this wouldn't quite map easily to a single `existingSecret`.
> 
> We could do the same thing as I did in #1403 with `env.TS3SERVER_SERVERADMIN_PASSWORD` and check if `env.SECRET` or `env.COOKIE_SECRET` is already set.
> 
> This way a user can set the secret directly with `env.SECRET` or use e.g. `env.SECRET.secretKeyRef`.

That's a good point, I didn't think of that. Sounds like a good idea to approach in a similar way as #1403 :+1:

2022-02-08 20:21 UTC, reitermarkus commented
Okay, I changed this now to depend on the `common` chart and refactored it to only use `env` instead of duplicating all variables in `values.yaml`.

2022-02-09 08:45 UTC, bjw-s requested changes

2022-02-09 08:45 UTC, bjw-s commented on charts/stable/traefik-forward-auth/Chart.yaml
> +      description: Added `common` chart dependency.
```suggestion
      description: **Breaking** Added `common` chart dependency. This will (potentially) require you to update your chart values.
```

2022-02-09 08:45 UTC, bjw-s commented on charts/stable/traefik-forward-auth/values.yaml
>    tag: ""
```suggestion
  # -- image tag
  # @default -- chart.appVersion
  tag:
```

2022-02-09 08:47 UTC, bjw-s requested changes

2022-02-09 08:47 UTC, bjw-s commented on charts/stable/traefik-forward-auth/ci/ct-values.yaml
> +  PROVIDERS_GOOGLE_CLIENT_SECRET: fakeclientsecret
```suggestion
  PROVIDERS_GOOGLE_CLIENT_SECRET: fakeclientsecret

middleware:
  enabled: false
```

It makes sense to enable the middleware by default, but in our CI environment we don't have that CRD.

2022-02-09 18:56 UTC, bjw-s approved these changes

2022-02-09 18:56 UTC, merged