[monica] App version bump to 3.6.1-apache.
k8s-at-home/charts pull request #1405
Opened 2022-02-06 23:36 UTC by samip5

**Description of the change** 

App version bump

**Benefits**

Newer upstream software

**Checklist** 
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [x] Variables have been documented in the `values.yaml` file.

2022-02-07 00:13 UTC, samip5 commented
Blocked by https://github.com/monicahq/monica/issues/5963.

2022-02-09 08:23 UTC, bjw-s requested changes

2022-02-09 08:23 UTC, bjw-s commented on charts/stable/monica/values.yaml
> +  tag: 3.7.0-apache
I would like to suggest changing this to the following (GitHub wouldn't let me create an actual suggestion for some reason), that way we only have to maintain the appVersion in the `Chart.yaml` file:

```yaml
  # -- image tag
  # @default -- chart.appVersion
  tag:
```

2022-02-09 09:21 UTC, bjw-s approved these changes

2022-02-09 09:29 UTC, merged