chore(homebridge): Set permissions for startup.sh to be executable
k8s-at-home/charts pull request #1466
Opened 2022-03-27 08:18 UTC by seanson

**Description of the change**

Currently we allow configuration of `startup.sh` through the `config` stanza in `values.yaml`, however this file is mounted with default permissions and so is not actually executable and fails silently. This adds a `defaultMode` configuration to the volume config which ensures the file will be executable at startup. 

**Benefits**

Ensures users running Homebridge will be able to configure and execute the startup script through the Helm configuration (commonly used for bootstrapping things like setting NET_CAP on the node binary).

**Possible drawbacks**

No drawbacks, as this fixes intended behaviour.

**Applicable issues**

- fixes #1465

**Additional information**

**Checklist**
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [X] Variables have been documented in the `values.yaml` file.

2022-03-29 04:58 UTC, bjw-s requested changes
Thanks for the quick PR!! Only a tiny change requested :-)

2022-03-29 04:58 UTC, bjw-s commented on charts/stable/homebridge/Chart.yaml
>      - kind: changed
Maybe change this to `fixed`

2022-03-30 00:56 UTC, seanson commented on charts/stable/homebridge/Chart.yaml
>      - kind: changed
Done!

2022-03-30 01:01 UTC, onedr0p submitted a review, later dismissed

2022-03-30 01:24 UTC, onedr0p approved these changes

2022-03-30 01:24 UTC, merged