[babybuddy] add chart: babybuddy
k8s-at-home/charts pull request #1471
Opened 2022-03-28 20:59 UTC by brianporeilly

Signed-off-by: Brian O'Reilly <brianporeilly@gmail.com>

**Description of the change**

Add new chart for babybuddy using the existing linuxserver docker image, which is a django application for caregivers of babies to track cares of their baby.

* https://github.com/babybuddy/babybuddy

**Benefits**

Allows deploying babybuddy via k8s-at-home

**Additional information**

**Checklist** 
- [ ] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [ ] Variables have been documented in the `values.yaml` file.

2022-03-29 21:54 UTC, onedr0p commented
Please make sure you complete the items in the checkboxes.

2022-03-30 10:37 UTC, onedr0p requested changes

2022-03-30 10:37 UTC, onedr0p commented on charts/incubator/babybuddy/values.yaml
> +  tag: 1.10.2
This should be:

```
# @default -- chart.appVersion 
tag:
```

2022-03-31 10:09 UTC, bjw-s approved these changes

2022-03-31 10:09 UTC, merged