[paperless] Updated values.yaml to add user/pass env
k8s-at-home/charts pull request #1496
Opened 2022-04-08 02:07 UTC by gandazgul

**Description of the change**

Updated values.yaml to add user/pass environment variables. Took me a long time to find these variables, they really should be here for other people to find.

**Benefits**

Clear configuration docs

**Possible drawbacks**

none I can think of

**Checklist** 
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [x] Variables have been documented in the `values.yaml` file.

2022-04-08 10:51 UTC, bjw-s requested changes
Thanks a lot for this! I didn't know this var existed either, and we've seen a few people ask about how to access it :) Some small changes requested, otherwise it's good to go.

2022-04-08 10:51 UTC, bjw-s commented on charts/stable/paperless/Chart.yaml
>      - kind: changed
Please remove the old changelog entries

2022-04-08 10:51 UTC, bjw-s commented on charts/stable/paperless/values.yaml
> +  # PAPERLESS_ADMIN_PASSWORD: admin
```suggestion
  # -- Username for the root user
  # PAPERLESS_ADMIN_USER: admin
  # -- Password for the root user
  # PAPERLESS_ADMIN_PASSWORD: admin
```

2022-04-10 04:21 UTC, gandazgul commented on charts/stable/paperless/Chart.yaml
>      - kind: changed
this is done.

2022-04-10 04:23 UTC, gandazgul commented
@bjw-s thank you for the review. I made the changes you requested, please take another look. 

It was tough to find those variables they are not mentioned anywhere, I'm going to go open a PR on paperless docs as well about this. I found these variables while looking through their tests and then where they are used in the code.

2022-04-10 09:02 UTC, bjw-s approved these changes

2022-04-10 09:02 UTC, merged