Added firefly-iii chart
k8s-at-home/charts pull request #1576
Opened 2022-05-21 12:15 UTC by bikram990

**Description of the change**

Add firefly-iii chart

**Benefits**

People will be able to deploy firefly-iii and manage their personal finance.

**Possible drawbacks**

NA

**Applicable issues**

NA

**Additional information**

**Checklist** 
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [ ] Variables have been documented in the `values.yaml` file.

2022-05-22 02:48 UTC, Truxnell commented
Hi @bikram990, thanks for the PR
Looks like you have some whitespace/end of file linting to do.  If you haven't, we suggest you install the repo pre-commit to ensure your PR will past the linting check.

2022-05-22 03:16 UTC, bikram990 commented
@Truxnell I've fixed the pre-commit linting issue.

2022-05-23 11:47 UTC, Truxnell requested changes
Just a few changes to suggest
Also note pinned issue https://github.com/k8s-at-home/charts/issues/1572 regarding planned future deprecation of database dependencies that we have upcoming in the common-library chart.  It may not affect this chart but its worth noting the maintenance issues that the extra database dependencies can cause maintainers.

2022-05-23 11:47 UTC, Truxnell commented on charts/stable/firefly-iii/Chart.yaml
> +appVersion: 5.6.14
```suggestion
appVersion: version-5.6.14
```
We recommend putting the image tag as the appVersion and leaving the tag blank in the values, as it inherits this line.

2022-05-23 11:47 UTC, Truxnell commented on charts/stable/firefly-iii/values.yaml
> +    schedule: "0 3 * * *"
```suggestion
    schedule: "0 3 * * *" # Schedule time in UTC
```
Worth mentioning to end users the cron will be scheduled in UTC time?

2022-05-23 11:47 UTC, Truxnell commented on charts/stable/firefly-iii/values.yaml
> +  tag: version-5.6.14
```suggestion
  # @default -- chart.appVersion
  tag:
```
These changes, coupled with the adjustment in chart.yaml will allow maintaing the image tag in one place not two

2022-05-23 11:47 UTC, Truxnell commented on charts/stable/firefly-iii/values.yaml
> +  # Enable cronjob for creating recurring transactions
```suggestion
  # -- Enable cronjob for creating recurring transactions
```
Any reason you havent gone with the `# --` style for all comments?  These allow the comments to be detected as field comments & render in helm-docs.  All your comments in the file are without the `--` which would generate a fairly empty doc.
(Ref: https://github.com/norwoodj/helm-docs)

2022-05-23 11:47 UTC, Truxnell commented on charts/stable/firefly-iii/values.yaml
> +    enabled: true
```suggestion
    enabled: false
```
We usually leave persistance false as default and allow the users to chose to enable.

2022-05-25 01:30 UTC, Truxnell approved these changes

2022-05-25 01:31 UTC, merged

2022-05-25 01:32 UTC, Truxnell commented
@bikram990 I've approved & merged.  
Have a look at how the readme generates - you can clean up anything that might need updating in a update (as it usually takes a bit to shake out changes with a new chart)

2022-05-25 02:59 UTC, Truxnell commented
@all-contributors please add @bikram990  for code