[dendrite] Per-component database settings
k8s-at-home/charts pull request #1581
Opened 2022-05-22 22:00 UTC by Omar007

**Description of the change**

This change allows database configuration to be set for each of the sub-components of Dendrite.

**Benefits**

This enabled use-cases such as:
- Use of a database other than SQLite or the included postgresql deployment
- Configure a completely separate database target for each component
- Configure database connection parameters per component

**Possible drawbacks**

None that I'm aware of. Backward compatibility is kept with the current logic.

**Applicable issues**

N/A

**Additional information**

N/A

**Checklist** 
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [X] Variables have been documented in the `values.yaml` file.

2022-05-23 10:41 UTC, Omar007 commented
Looks like the CI is failing on something unrelated to this change? :thinking: 

```
time="2022-05-23T06:09:42Z" level=info msg="Starting \"syncapi\" component"
time="2022-05-23T06:09:42Z" level=error msg="Configuration error: You have tried to enable open registration without any secondary verification methods (such as reCAPTCHA). By enabling open registration, you are SIGNIFICANTLY increasing the risk that your server will be used to send spam or abuse, and may result in your server being banned from some rooms. If you are ABSOLUTELY CERTAIN you want to do this, start Dendrite with the -really-enable-open-registration command line flag. Otherwise, you should set the registration_disabled option in your Dendrite config."
time="2022-05-23T06:09:42Z" level=fatal msg="Failed to start due to configuration errors"
```

2022-05-29 14:47 UTC, Jonnobrow commented
For some reason the syncapi is pulling the latest version rather than v0.8.1. In [v0.8.3](https://github.com/matrix-org/dendrite/releases/tag/v0.8.3) there was a modification to make open registration harder. 

So to fix:
- Pin syncapi version
- **and** Fix the config to add in the missing fields and bump AppVersion to v0.8.6

2022-05-29 15:08 UTC, Jonnobrow commented
I have opened a PR with a fix: https://github.com/Omar007/charts/pull/1

2022-05-30 09:18 UTC, Jonnobrow reviewed
Couple of things I missed by the looks of it

2022-05-30 09:18 UTC, Jonnobrow commented on charts/incubator/dendrite/values.yaml
>    args: "userapi"
Missing value.

```suggestion
  args: "userapi"
  bcrypt_cost: 10
```

2022-05-30 09:18 UTC, Jonnobrow commented on charts/incubator/dendrite/values.yaml
>    # -- Enable polylith deployment
```suggestion
  # -- Enable polylith deployment
  report_stats:
    enabled: 
    endpoint: 
```

2022-06-01 13:17 UTC, Truxnell commented
LGTM.  However, are we confident it wont be breaking to users - i.e. is a minor bump appropriate?
It does look to me like it wont be breaking however i do note this PR would change 'registration_disabled' from false to true for users?

2022-06-02 13:15 UTC, Truxnell requested changes

2022-06-02 13:18 UTC, Truxnell commented
I may be taking a over-abundance of caution, but do we do similar to the reiview, a major semver + callout the registration change?
Happy to go either way, I'm not familiar with the chart, but we do like to follow SemVer closely.

2022-06-02 15:47 UTC, Omar007 commented
I have bumped it up to 0.8.7 due do some important fixes in Dendrite itself and included both chart suggestions bumping it to 5.0.0 and explicitly mentioning the defaults change in the changelog :+1:

2022-06-02 23:35 UTC, Truxnell approved these changes

2022-06-02 23:50 UTC, merged

2022-06-02 23:51 UTC, Truxnell commented
Thanks for the PR @Omar007 & assistance @Jonnobrow 

@all-contributers, can you add @Omar007 for code.

2022-06-02 23:52 UTC, Truxnell commented
@all-contributors, can you add @Omar007  for code.

2022-06-03 10:06 UTC, Truxnell commented
@all-contributors please add @Omar007  for code