[send] Added timvisee Send chart
k8s-at-home/charts pull request #1586
Opened 2022-05-28 01:53 UTC by geraldwuhoo

Signed-off-by: geraldwuhoo <gerald@geraldwu.com>

**Description of the change**

Add [Send](https://gitlab.com/timvisee/send) chart

**Benefits**

People will be able to deploy Send, a simple drag-and-drop file sharing service with client-side encryption.

**Possible drawbacks**

NA

**Applicable issues**

NA

**Additional information**

**Checklist** 
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [x] Variables have been documented in the `values.yaml` file.

2022-05-28 16:49 UTC, bjw-s requested changes
Thanks for the PR! Just a tiny change requested :)

2022-05-28 16:49 UTC, bjw-s commented on charts/stable/send/values.yaml
> +  tag: v3.4.20
```suggestion
  tag:
```

2022-05-28 22:44 UTC, geraldwuhoo commented
Thanks! For future reference, why not include the tag in the base `values.yaml`?

2022-05-29 00:34 UTC, geraldwuhoo commented on charts/stable/send/values.yaml
> +  tag: v3.4.20
Done

2022-05-30 05:50 UTC, bjw-s commented
Thank you for updating! 

> Thanks! For future reference, why not include the tag in the base `values.yaml`?

The reason for this is that the value gets populated by the `appVersion` field from `Chart.yaml` metadata by default when the field is empty. We had quite some charts in the past where the `appVersion` metadata would differ from the `image.tag` value. So by leaving it empty by default we ensure that they are always in sync (and only have to update the application version in one spot) :) Users can still manually override/pin the value by specifying a value themselves.

2022-05-30 05:50 UTC, bjw-s approved these changes

2022-05-30 05:50 UTC, merged

2022-05-30 05:51 UTC, bjw-s commented
@all-contributors Please add @geraldwuhoo for code