[snapcast] Adding new chart
k8s-at-home/charts pull request #1615
Opened 2022-06-09 18:34 UTC by lanquarden

Signed-off-by: lanquarden <lanquarden@gmail.com>

**Description of the change**

Adding snapcast (server) helm chart

**Benefits**

Easily run a snapcast server in your cluster

**Possible drawbacks**

It's not an official docker container from the project, I've picked one that is following the release cadence and versions the containers.

**Applicable issues**

- fixes #

**Additional information**

This is just a bare bones version, manually installed with helm from the repo and it's running. As I learn how to successfully deploy this together with a mopidy chart I'll try to find a way to poor that back into the documentation/values.yaml

My first attempt at creating a helm chart, the common chart and the wealth of examples make this a breeze!

**Checklist** 
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [X] Variables have been documented in the `values.yaml` file.

2022-06-10 03:19 UTC, Truxnell commented
Thanks @lanquarden 

Looks like you just have a little linting to do.
`Error: [colons] too many spaces after colon`

2022-06-10 10:18 UTC, lanquarden commented
Linting issue should be fixed now

2022-06-13 11:47 UTC, Truxnell requested changes
Few minor changes/linting, which i think you may have already done while i was reviewing!

2022-06-13 11:47 UTC, Truxnell commented on charts/incubator/snapcast/Chart.yaml
> +- snapserver
```suggestion
  - snapcast
  - snapserver
```

2022-06-13 11:47 UTC, Truxnell commented on charts/incubator/snapcast/Chart.yaml
> +- https://github.com/badaix/snapcast
```suggestion
  - https://github.com/badaix/snapcast
```

2022-06-13 11:47 UTC, Truxnell commented on charts/incubator/snapcast/Chart.yaml
> +  email: lanquarden@gmail.com
```suggestion
  - name: lanquarden
    email: lanquarden@gmail.com
```

2022-06-13 11:47 UTC, Truxnell commented on charts/incubator/snapcast/Chart.yaml
> +  version: 4.4.2
```suggestion
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
```

2022-06-13 11:47 UTC, Truxnell commented on charts/incubator/snapcast/values.yaml
> +  tag: v0.26.0
```suggestion
  tag:
```
This inherits from the `Chart.yaml` so we prefer to leave this blank -  then you only have to maintain version once not twice.

2022-06-13 12:26 UTC, merged