[teamspeak] feat: Can now change metric exporter remote
k8s-at-home/charts pull request #1621
Opened 2022-06-17 00:44 UTC by MattJeanes

**Description of the change**

You can now specify the remote of the metric exporter for the teamspeak chart, this allows you to use it when running on non-standard query ports which is currently not possible.

**Benefits**

You will now be able to use the metric exporter when running teamspeak on non-standard query ports.

**Possible drawbacks**

N/A

**Applicable issues**

N/A

**Additional information**

N/A

**Checklist** 
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [x] Variables have been documented in the `values.yaml` file.

2022-06-17 07:38 UTC, bjw-s requested changes
Thanks for taking the time to submit a PR :raised_hands:, I've left some remarks/questions in my review.

2022-06-17 07:38 UTC, bjw-s commented on charts/incubator/teamspeak/Chart.yaml
> +appVersion: 3.13.7
```suggestion
appVersion: 3.14.0
```
Since this is not really a bug fix, the version number should be bumped accordingly

2022-06-17 07:38 UTC, bjw-s commented on charts/incubator/teamspeak/Chart.yaml
> +      description: Can now change metric exporter remote
```suggestion
      description: Adds support for setting the metric exporter remote
```

2022-06-17 07:38 UTC, bjw-s commented on charts/incubator/teamspeak/values.yaml
> +      remote: localhost:10011
I don't know the app, so I just want to make sure that this is a sensible default that will not break peoples existing installs?

2022-06-17 14:53 UTC, MattJeanes commented
Hi @bjw-s thank you for your review

I accidentally updated the appVersion not the chart version so I have corrected this now - it looks like this is what was failing the CI as well.

I've also responded to your code comments 🙂

2022-06-20 14:10 UTC, bjw-s approved these changes

2022-06-20 14:10 UTC, merged

2022-06-20 14:59 UTC, MattJeanes commented
Many thanks! 🙂