common - add ingressclass name
k8s-at-home/charts pull request #441
Opened 2020-12-28 22:39 UTC by angryninja48

Signed-off-by: Jon Baker <jonbaker85@gmail.com>

**Description of the change**

Adds in ingressclass name to the spec field

https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/

**Benefits**

Able to use ingress class in K8 >= 1.18 

**Possible drawbacks**

None

**Applicable issues**

- fixes #

**Additional information**

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [ ] Chart is using our [common](https://github.com/k8s-at-home/charts/tree/master/charts/common) library as a dependency.
- [ ] (optional) Variables are documented in the README.md

2020-12-29 01:17 UTC, onedr0p commented
You will need to make the logic compare kubernetes versions because it breaks linting. 

See this comment
https://github.com/k8s-at-home/charts/blob/master/charts/common/templates/lib/chart/_capabilities.tpl#L81

2020-12-29 01:19 UTC, onedr0p commented
Additionally you _should_ be able to use this following logic for that field, right?

https://github.com/k8s-at-home/charts/blob/master/charts/common/templates/classes/_ingress.tpl#L46

2020-12-29 01:26 UTC, onedr0p commented on charts/common/Chart.yaml
> +version: 2.2.1
This should be 2.2.0

2020-12-29 01:26 UTC, onedr0p commented on charts/common/templates/classes/_ingress.tpl
> +  {{- if or (.Capabilities.APIVersions.Has "networking.k8s.io/v1/IngressClass") (.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/IngressClass") }}
See other comment in PR

2020-12-29 01:27 UTC, onedr0p requested changes
Small changes

2020-12-29 01:58 UTC, angryninja48 reviewed
Updated to follow existing logic

2020-12-29 08:45 UTC, bjw-s commented
Thanks for the contribution!
I have changed the base branch to `common-next` so that we can group a few changes together for the next release of the `common` chart.

2020-12-30 07:07 UTC, bjw-s approved these changes

2020-12-30 07:07 UTC, merged