[icantbelieveitsnotvaletudo] Fix link in readme
k8s-at-home/charts pull request #484
Opened 2021-01-09 07:20 UTC by igas

Fix of the broken link

**Benefits**

No more github 404

**Possible drawbacks**

**Applicable issues**

- fixes #

**Additional information**

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [ ] Chart is using our [common](https://github.com/k8s-at-home/charts/tree/master/charts/common) library as a dependency.
- [ ] (optional) Variables are documented in the README.md

2021-01-09 13:44 UTC, onedr0p requested changes
Thanks for the fix but you will need to bump the patch version of the chart in Chart.yaml

2021-01-10 19:34 UTC, bjw-s commented
> Thanks for the fix but you will need to bump the patch version of the chart in Chart.yaml

Once the CI modifications (#487 ) are merged, the bump can probably be skipped.

2021-01-11 00:10 UTC, igas commented
@bjw-s nice one! I'll wait for it, don't want to bump chart for unrelated commit.

2021-01-11 06:40 UTC, bjw-s approved these changes

2021-01-11 06:40 UTC, merged