Move duplicati to Common-Chart
k8s-at-home/charts pull request #644
Opened 2021-03-06 19:16 UTC by Ornias1993

**Description of the change**

This should be most of the work to port Duplicati to the Common-Chart.

**Benefits**

**Possible drawbacks**

**Applicable issues**

- fixes #

**Additional information**

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [ ] (optional) Chart is using our [common](https://github.com/k8s-at-home/charts/tree/master/charts/common) library as a dependency.
- [ ] (optional) Variables are documented in the README.md

2021-03-06 20:41 UTC, rolfberkenbosch requested changes
If you add my changes to the code, then it will works also with the PVC.
I have just test the code with my changes, and it works!

2021-03-06 20:41 UTC, rolfberkenbosch commented on charts/duplicati/values.yaml
> +    mountPath: /config
```suggestion
    mountPath: /config
    accessMode: ReadWriteOnce
    size: 1Gi
```

2021-03-06 20:41 UTC, rolfberkenbosch commented on charts/duplicati/values.yaml
> +    mountPath: /source
```suggestion
    mountPath: /source
    accessMode: ReadWriteOnce
    size: 1Gi
```

2021-03-06 20:41 UTC, rolfberkenbosch commented on charts/duplicati/values.yaml
> +    mountPath: /backups
```suggestion
    mountPath: /backups
    accessMode: ReadWriteOnce
    size: 1Gi
```

2021-03-06 21:24 UTC, Ornias1993 commented
@rolfberkenbosch I'm not going to finish this (i've more important projects that need my attention currently), it's just a PoC to make clear it has nothing to do with refactoring, like you suggested.

You can copy it and finished it if you like.

Two notes:
- RWO is already the default so doesn't have to be added afaik
- specifying a size is not needed at all and is normally not done on all the other common-dependent charts

2021-03-06 21:24 UTC, closed without merging

2021-03-07 08:32 UTC, bjw-s commented
If you never meant to work on this (for it to be actually merged), why did you create a PR for it? Was it really just to prove a point and "prove" that you are right? You could have just linked to your branch instead of creating this, and even that is debatable.

We have asked you a few times before to remain cordial and be kind to the people that are contributing to our community. Please consider this your final explicit warning.

2021-03-07 08:47 UTC, Ornias1993 commented
> If you never meant to work on this (for it to be actually merged), why did you create a PR for it? Was it really just to prove a point and "prove" that you are right? You could have just linked to your branch instead of creating this, and even that is debatable.
> 
> We have asked you a few times before to remain cordial and be kind to the people that are contributing to our community. Please consider this your final explicit warning.

Its called “helping out” AND proving a point. It never was a full blown PR, it always was a draft aka PoC.

I was never planning **not** to finish it btw, I never said so. Other things came up that are more important than spinning up a vm/container just to generate a wiki. 

Maybe before warning people, try and look at the intend of people FIRST.

2021-03-07 15:12 UTC, onedr0p commented
> To be clear: i’m always direct, if I see BS, I call it BS. Though I prefer to cleanup along the wag while at it, like this draft.

We want this community to be friendly and helpful. We're all not geniuses and sometimes we can say things that could be wrong or could be construed as bullshit.

The way you comment or provide feedback on issues is often unacceptable to us and are viewed as hostile behavior.

Please work on your communication skills.

2021-03-14 22:27 UTC, onedr0p commented
@all-contributors please add @Ornias1993 for code