Merge pull request #10 from k8s-at-home/master
k8s-at-home/charts pull request #676
Opened 2021-03-15 09:58 UTC by auricom

[Tdarr](url) chart based on the dependent 'common' chart.
Distributed Transcoding System

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] (optional) Chart is using our [common](https://github.com/k8s-at-home/charts/tree/master/charts/common) library as a dependency.
- [x] (optional) Variables are documented in the README.md

2021-03-15 22:33 UTC, onedr0p requested changes

2021-03-15 22:33 UTC, onedr0p commented on charts/tdarr/Chart.yaml
> +  - joplin
tags need updating

2021-03-15 22:33 UTC, onedr0p commented on charts/tdarr/.helmignore
> +OWNERS
also need *.gotmpl

2021-03-16 01:39 UTC, auricom commented on charts/tdarr/Chart.yaml
> +  - joplin
Whoopsie, fixed!

2021-03-16 02:04 UTC, auricom commented
Github action failed due to network issue, a manual trigger should be successful

2021-03-16 11:24 UTC, onedr0p approved these changes

2021-03-16 11:24 UTC, merged