[duplicati] migrate to common
k8s-at-home/charts pull request #822
Opened 2021-04-23 02:39 UTC by nicholaswilde

Signed-off-by: Nicholas Wilde <ncwilde43@gmail.com>

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

2021-04-23 04:56 UTC, nicholaswilde commented
Should I add `influxdb` as a dependency?

2021-04-24 10:04 UTC, onedr0p requested changes

2021-04-24 10:04 UTC, onedr0p commented on charts/stable/duplicati/values.yaml
> +  tag: v2.0.5.1-2.0.5.1_beta_2020-01-18-ls98
I'd make this latest, it's such a cluster f of a tag name.

2021-04-24 10:04 UTC, onedr0p commented on charts/stable/duplicati/Chart.yaml
>  appVersion: v2.0.5.1
latest here too, for now...

2021-04-24 10:04 UTC, onedr0p commented
> Should I add `influxdb` as a dependency?

Nope, it should not be needed.

2021-04-25 07:18 UTC, onedr0p approved these changes

2021-04-25 07:30 UTC, merged