[modem-stats] migrate to common
k8s-at-home/charts pull request #823
Opened 2021-04-23 04:36 UTC by nicholaswilde

Signed-off-by: Nicholas Wilde <ncwilde43@gmail.com>

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

2021-04-23 04:56 UTC, nicholaswilde commented
Should I add `influxdb` as a dependency?

2021-04-24 10:08 UTC, onedr0p requested changes

2021-04-24 10:08 UTC, onedr0p commented on charts/stable/modem-stats/Chart.yaml
> +  - name: influxdb
Even though this uses influx, I don't think I'd include it here as a dep.

2021-04-25 14:23 UTC, onedr0p approved these changes

2021-04-25 15:00 UTC, merged