[thelounge] Update to Commons 3.0.0
k8s-at-home/charts pull request #946
Opened 2021-06-08 22:40 UTC by rwaltr

**Description of the change**

Up deps to commons 3.0.0

**Additional information**

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [ ] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

2021-06-08 22:42 UTC, rwaltr commented
Made for #942

2021-06-09 07:26 UTC, bjw-s requested changes
Thanks for creating the PR! I've suggested a rewording of the changelog entry.
Also, could you add the helm docstrings to the `values.yaml` file? That will make the README / values file a little bit more clear (at the expense of a small bit of "duplicate" documentation). Feel free to steal the text from the airsonic chart 😛

2021-06-09 07:26 UTC, bjw-s commented on charts/stable/thelounge/README_CHANGELOG.md.gotmpl
> +- Updated to Commons 3.0.0
```suggestion
- **BREAKING**: Upgraded the common library dependency to version 3.0.0. This introduces several breaking changes (`service`, `ingress` and `persistence` keys have been refactored).
  Be sure to check out the [library chart](https://github.com/k8s-at-home/library-charts/blob/common-3.0.0/charts/stable/common/) for the up-to-date values.
```

2021-06-09 22:01 UTC, rwaltr commented
> Thanks for creating the PR! I've suggested a rewording of the changelog entry.
> Also, could you add the helm docstrings to the `values.yaml` file? That will make the README / values file a little bit more clear (at the expense of a small bit of "duplicate" documentation). Feel free to steal the text from the airsonic chart stuck_out_tongue

Ill take a look at the docstrings today

2021-06-10 06:59 UTC, bjw-s approved these changes

2021-06-10 06:59 UTC, merged